version: '2.1'
services:
  web:
    stdin_open: true
    build: .
    ports:
      - '3000:3000'
    volumes:
      - .:/var/www
      - /var/www/node_modules
    command: "yarn start"
    env_file:
      - .env
